sudo: required
services:
  - docker
language: python
python:
  - "3.7"
before_install:
  - python3 -m pip install --upgrade pip setuptools wheel
install:
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html#the-travis-yml-file
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Install nextstrain cli
  - conda install -n base -c conda-forge mamba --yes
  - conda activate base
  - mamba create -n nextstrain -c bioconda nextstrain-cli --yes
  - conda activate nextstrain
  - mamba install -c conda-forge -c bioconda augur auspice nextalign snakemake git --yes
  - nextstrain version
  - nextstrain check-setup
  - nextstrain update
script:
  - mkdir -p data/
  - cp -v example_data/zika.fasta data/
  - nextstrain build .
