# Optional configs used by Nextstrain team
# Params for uploads
upload:
  # Upload params for AWS S3
  s3:
    # AWS S3 Bucket with prefix
    dst: 's3://nextstrain-data/files/workflows/mpox'
    # Mapping of files to upload, with key as remote file name and the value
    # the local file path relative to the ingest directory.
    files_to_upload:
      genbank.ndjson.xz: data/genbank.ndjson
      all_sequences.ndjson.xz: data/sequences.ndjson
      metadata.tsv.gz: results/metadata.tsv
      sequences.fasta.xz: results/sequences.fasta
      alignment.fasta.xz: data/alignment.fasta
      insertions.csv.gz: data/insertions.csv
      translations.zip: data/translations.zip

    cloudfront_domain: 'data.nextstrain.org'

# Toggle for Slack notifications
send_slack_notifications: True

# Toggle for triggering builds
trigger_rebuild: True
