name: CI

on:
  - push
  - pull_request

jobs:
  pathogen-ci:
    strategy:
      matrix:
        runtime: [docker, conda]
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      runtime: ${{ matrix.runtime }}
      run: |
        nextstrain build \
          phylogenetic \
          --configfile build-configs/ci/profiles_config.yaml
      artifact-name: output-${{ matrix.runtime }}
      artifact-paths: |
        phylogenetic/auspice/
        phylogenetic/results/
        phylogenetic/benchmarks/
        phylogenetic/logs/
        phylogenetic/.snakemake/log/